### PR TITLE
Make database name selectable and configurable

### PR DESCRIPTION
**Pull request by vzool**

### CODE REVIEW

**Comment by zigazajc007** [comment]
It's a little more than just that as database name in database.sql file is currently hard codded.

https://github.com/Rabbit-Company/Passky-Server/blob/main/database/database.sql

**Comment by vzool** [comment]
Ah, I missed that, but we can Ignore creating and mention the database in that file, SQL will still works as expected.

> It's a little more than just that as database name in database.sql file is currently hard codded.
> 
> https://github.com/Rabbit-Company/Passky-Server/blob/main/database/database.sql

Ah, I missed that, but we can Ignore creating and mention the database in that file, SQL will still works as expected.

**Comment by zigazajc007** [comment]
The problem is that this is needed for docker. As everything from this file will be auto executed when docker container starts.

**Comment by zigazajc007** [comment]
I would need to perform some tests, to see if everything will still work as expected in MariaDB docker container.

**Comment by vzool** [comment]
I think I did it 🤣✌️

**Comment by vzool** [comment]
> The problem is that this is needed for docker. As everything from this file will be auto executed when docker container starts.

Yes, I didn't realized that, but with last [commit](https://github.com/Rabbit-Company/Passky-Server/pull/9/commits/f029578abe7e158b4a67723032da88b030027c94) in this [PR](https://github.com/Rabbit-Company/Passky-Server/pull/9) the application database name now is updateable for docker containers according to MYSQL_DATABASE in .env

**Comment by vzool** [comment]
> I would need to perform some tests, to see if everything will still work as expected in MariaDB docker container.

I think we need test units to cover all API calls, so we can make a big jumps in development cycles.

**Comment by zigazajc007** [comment]
> > I would need to perform some tests, to see if everything will still work as expected in MariaDB docker container.
> 
> I think we need test units to cover all API calls, so we can make a big jumps in development cycles.

I want to keep code for the Passky Server as clean as possible.

You can use PasskyAPI-JS to perform API calls. https://github.com/Rabbit-Company/PasskyAPI-JS/blob/main/example/index.html

**Comment by zigazajc007** [comment]
MYSQL_DATABASE placeholder in database.sql file will now be replaced only when docker container starts and with duplicated file inside the container. So installers wouldn't interact with your system in any way except creating .env file. This also means if you just change database name in .env file without running installer it would work.

**Comment by zigazajc007** [comment]
Thanks for your contribution, I will now Merge pull request and make more tests before it goes to production.

**Pull request merged**
